### ISSUE TITLE
dnceng-official broken

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#765] opened 2023-09-01 18:53 UTC
The build is broken but build monitor is not working for this repo https://github.com/dotnet/dnceng/issues/760. Investigate and fix.

https://dnceng.visualstudio.com/internal/_build/results?buildId=2257959&view=results

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed regressions in the CI pipeline caused by auth library changes

**Comment by riarenas** [comment] 2023-09-01 18:56
This is most likely a consequence of the new auth libraries, and will probably need some reaction to the code in both the Grafana publishing and the scenario tests.

**Comment by riarenas** [comment] 2023-09-01 21:00
This is a side effect of https://github.com/dotnet/dnceng/pull/758.

* for the secret-manager scenario tests, we don't initialize the azure CLI, which is causing failures with the new flow of trying to obtain the cli credentials first.
* For the grafana publishing. It looks like we need to update our authentication code for the new libraries. 

We could revert #758, but that would mean making secret-manager break during synchronization and validation runs. I think it's less impactful if we leave this repo broken until we fix things up.

**Comment by premun** [comment] 2023-09-08 13:48
Sorry, totally missed this.

> I think it's less impactful if we leave this repo broken until we fix things up.

I agree.

Having a quick glance - we're probably failing to connect to a keyvault here: https://github.com/dotnet/dnceng/blob/bf68694c553f692e4f8b50883f79ffcd5ec64e5e/src/Monitoring/Sdk/DeployPublisher.cs#L284

**Comment by premun** [comment] 2023-09-08 13:54
This bit is also interesting:

```
error MSB4018: Azure.Identity.AuthenticationFailedException: ClientSecretCredential authentication failed: The type initializer for 'Microsoft.Identity.Client.Platforms.net6.MsalJsonSerializerContext' threw an exception. [D:\a\_work\1\s\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj]
error MSB4018:  ---> System.TypeInitializationException: The type initializer for 'Microsoft.Identity.Client.Platforms.net6.MsalJsonSerializerContext' threw an exception. [D:\a\_work\1\s\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj]
error MSB4018:  ---> System.MissingMethodException: Method not found: 'System.Text.Json.JsonEncodedText System.Text.Json.JsonEncodedText.Encode(System.String, System.Text.Encodings.Web.JavaScriptEncoder)'. [D:\a\_work\1\s\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj]
error MSB4018:    at Microsoft.Identity.Client.Platforms.net6.MsalJsonSerializerContext..cctor() [D:\a\_work\1\s\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj]
```

Could be that the new identity library doesn't work well with the `System.Text.Json` version we have?

**Comment by premun** [comment] 2023-09-08 14:27
Fix for the Grafana stage is here: https://github.com/dotnet/dnceng/pull/789

The other part looks like it might be trying to use the interactive login in a CI and expiring. Will have a look at it too.

**Comment by premun** [comment] 2023-09-11 07:45
The Grafana deployment is fixed but the SecretManager scenario tests remain. Possibly, the problem there lies in the fact we're not running the tests as an AzureCLI pipeline task.
Regardless, the Chained credential should fail to get a token via AzureCLI and then try the other but somehow it times out. I suspect some interactive mode is turned on and hanging.

**Comment by missymessa** [comment] 2023-09-12 15:43
Current failure is occurring on this line when iterating over the list: https://github.com/dotnet/dnceng/blob/3021e2c6ff85c412ae399d5a954839bf460bba1f/src/SecretManager/Microsoft.DncEng.SecretManager/StorageTypes/AzureKeyVault.cs#L61

Able to reproduce this locally

**Comment by missymessa** [comment] 2023-09-15 16:38
PR here: https://github.com/dotnet/dnceng/pull/820

**Comment by missymessa** [comment] 2023-09-18 16:19
Secret Manager tests were fixed. The storage account issue was fixed. Now, the DotNet Eng Status API on staging is broken: https://dotneteng-status-staging.azurewebsites.net/

**Comment by garath** [comment] 2023-09-20 00:01
I brought the site back by swapping slots, then from there generated a token the notification system could use. Both performed as expected in the latest dnceng build [2270493](https://dev.azure.com/dnceng/internal/_build/results?buildId=2270493&view=results). So, looks like we're good to go now.

**Comment by garath** [comment] 2023-09-21 20:56
Things have been stable! Closing.

**Closed by garath** 2023-09-21 20:56 UTC
Labels: Build Failed, Ops - First Responder
