### ISSUE TITLE
Azdo Issue #5889

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2093] opened 2024-02-27 16:21 UTC
https://dev.azure.com/dnceng/internal/_workitems/edit/5889

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment] 2024-03-21 23:53
@missymessa didn't you address this issue in all dotnet/arcade branches❔

**Comment by missymessa** [comment] 2024-03-22 20:39
Yeah, this should've been handled. Ricardo, are we still seeing this in places, or was this a dupe of the one we fixed?

**Closed** 2024-04-01 16:42 UTC
