### ISSUE TITLE
Investigate windows.vs2022.amd64 image (broken after adding MSYS2?)

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#728] opened 2023-08-29 00:12 UTC
The dotnet/runtime repository is experiencing failures in their internal builds with error messages informing of missing Visual Studio components. This started happening on 8/23, the day of the image rollouts, so we should investigate if this is related to the image updates. The only change to the VIsual Studio images involved adding the new MSYS2 artifact.

Example builds: 
https://dev.azure.com/dnceng/internal/_build/results?buildId=2254189&view=logs&j=f0eef5b9-7c04-5d73-f640-8f9169722c68&t=705acc87-2e8e-5c6c-4b31-55232ead5306&l=93

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Removed MSYS2 from windows.vs2022.amd64.* images, to fix broken images

**Comment by riarenas** [comment] 2023-08-29 16:20
I'm going to steal this issue and use it to track anything I find regarding this image.

**Comment by riarenas** [comment] 2023-08-29 17:41
While this is investigated, I manually updated the 1es images resources we use for this image, and told it to go back to use the LKG image from 8/22. https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/1ESHostedPoolImagesWestUS-rg/providers/Microsoft.CloudTest/images/windows.vs2022.amd64/image

**Comment by riarenas** [comment] 2023-08-29 21:55
I have created three different vms trying to repro the issues. No luck so far. I'll give it a couple more tries tomorrow.

**Comment by riarenas** [comment] 2023-08-30 14:52
The same errors are still happening even with the reverted image: https://dnceng.visualstudio.com/internal/_build/results?buildId=2256086&view=logs&j=c08f4d29-06c1-5e3b-b94b-1702412980f1&t=f529fb3d-1463-5ee2-5dfd-063237ddec28&l=568. This makes me suspicious of this being caused by the image updates.

**Comment by riarenas** [comment] 2023-08-31 15:53
We've confirmed the error is as indeterministic with the 8/16 image as it was with newer images, which means this is not related at all with the image update. This is currently blocked on the runtime team performing additional investigations on the vs installations.

**Comment by riarenas** [comment] 2023-09-07 15:54
We have a response from the VSSetup team:

>This issue has cropped up due to the VS Setup team re-enabling automatic extension updates in certain cases for Dev17.

>It seems the root cause for this is in the agent image maintained by 1ES. The agent, when built, leaves the VSIX Auto Update task enabled - this normally happens if the image build process installs extensions after an VS installation is complete. A CI build start causes the agent to 'boot', triggering the task and blocking VS from being used until any extension updates are completed. The recommended fix would be to ask 1ES to update their build agent imaging process to ensure the scheduled task is disabled by using the command I highlighted below (or to run the task prior to completing the build agent image). We'd be happy to get involved with any conversations that happen with 1ES to provide guidance there.

>An alternative mitigation for the time being would be to update the .NET build process to check for the launchability of VS on start with vswhere (and look for the presence of VSIXAutoUpdate.exe / devenv.exe) with a reasonable timeout (5-7min or so) to let the update process complete if and when it kicks off.
```

I will create issues on our end to disable all forms of auto update from Visual studio in our VS workloads artifacts, and will also attempt to push on 1ES to apply the same.

**Comment by riarenas** [comment] 2023-09-07 16:02
To kill the vsix auto update task: `schtasks /change /tn "\Microsoft\VisualStudio\VSIX Auto Update" /disable`

To disable updates altogether, let's attempt the reg keys in https://learn.microsoft.com/en-us/visualstudio/install/configure-policies-for-enterprise-deployments?view=vs-2022

**Comment by riarenas** [comment] 2023-09-07 16:21
I think we can close this issue as we have something actionable to do here, and we now understand why reverting the image versions, or even using newer images doesn't help here.

**Closed by riarenas** 2023-09-07 16:21 UTC
Labels: Ops - First Responder
