### ISSUE TITLE
Signing validation in `dotnet-arcade-validation-official` is failing

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#904] opened 2023-09-27 11:42 UTC
The [dotnet-arcade-validation-official](https://dev.azure.com/dnceng/internal/_build?definitionId=282) is failing for some time already and this is blocking arcade updates.

Seems like MSBuild is not new enough: https://dev.azure.com/dnceng/internal/_build/results?buildId=2271252&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=fb192a8b-e433-5fc8-e2b0-276ab015e7d5

**Comment by missymessa** [comment] 2023-10-03 17:40
If we need to update MSBuild, then probably a duplicate of: https://github.com/dotnet/arcade/issues/14031

**Comment by missymessa** [comment] 2023-10-05 21:01
Resolved with the MSBuild update.

**Closed by missymessa** 2023-10-05 21:01 UTC
