### ISSUE TITLE
2023-10 Artifact Maintenance

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/dnceng#1151] opened 2023-10-24 06:03 UTC
### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Regular update for 2023-10 Artifact Maintenance.

**Comment by v-zheyan** [comment] 2023-10-24 06:03
Here is the task in Azure: https://dev.azure.com/dnceng/internal/_workitems/edit/5663

**Comment by garath** [comment] 2023-10-26 06:46
This seems to be a duplicate of #1150. Intentional?

**Comment by v-zheyan** [comment] 2023-10-26 07:44
> This seems to be a duplicate of #1150. Intentional?
Yes, we usually create a new one since the pipeline always detect the keyword **Release Note Description**, In previous we cannot edit the comments created by bot like https://github.com/dotnet/dnceng/issues/1139, but now seems can edit it, I will take a try next time, If successfully, only one github issue which created by bot will be kept in the future.

**Closed** 2023-11-08 01:31 UTC
Labels: Ops - Compliance
