### ISSUE TITLE
Docker EOL Report should reflect EOL annotation status of referenced images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dnceng#4350] opened 2024-10-25 19:22 UTC
The container images managed by the .NET team are [in the process of being annotated with EOL data](https://github.com/dotnet/docker-tools/issues/1201) as appropriate. This is already rolled out for the images in the `mcr.microsoft.com/dotnet-buildtools/prereqs` repo, which is what is reported on by the Docker EOL Report.

The current data showing in the report is inaccurate because it does not take into account these annotations. For example, filtering the report to show tags containing `windowsservercore-ltsc2022-helix-webassembly`, you'll see a reference to the tag `windowsservercore-ltsc2022-helix-webassembly-20240702174122-7aba2af` by [dotnet/runtime](https://github.com/dotnet/runtime/blob/8f6ac065d5965efebe1624db2117b82dbbaa6cd3/eng/pipelines/libraries/helix-queues-setup.yml#L183).

The report shows that it's not yet EOL.

But the actual image has been annotated with an EOL date:

```shell
$ oras discover mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2022-helix-webassembly-20240702174122-7aba2af --format json
{
  "manifests": [
    {
      "reference": "mcr.microsoft.com/dotnet-buildtools/prereqs@sha256:7aaf16098579c7f8c740f8223fd6ebdb6a4e688f4120decd1e016c36f45dab41",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:7aaf16098579c7f8c740f8223fd6ebdb6a4e688f4120decd1e016c36f45dab41",
      "size": 783,
      "annotations": {
        "org.opencontainers.image.created": "2024-09-30T20:32:27Z",
        "vnd.microsoft.artifact.lifecycle.end-of-life.date": "2024-08-02"
      },
      "artifactType": "application/vnd.microsoft.artifact.lifecycle"
    }
  ]
}
```

The report should reflect this EOL date.

**Comment by MichaelSimons** [comment] 2024-10-28 16:07
@mthalman - this is a duplicate of https://github.com/dotnet/dnceng/issues/3615.  Can you close this, I don't have permission to.

**Closed** 2024-10-28 16:50 UTC
