### ISSUE TITLE
dotneteng-status-staging down

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#1963] opened 2024-02-06 18:33 UTC
The dotneteng-status-staging site is down. The Azure alert fired this morning. Site loads with the message "App service is offline".

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment] 2024-02-06 18:37
Maybe the slot switching problem we've seen in the past?

**Comment by garath** [comment] 2024-02-07 17:26
Slot-swap brought the site back. Surely it is running old code, though. 

I do not have lots of knowledge in how app service deployments work, so I'm going to spend a bit of time here on FR to see if I can fill that gap.

**Comment by garath** [comment] 2024-02-12 19:42
The site is back up so the urgency is resolved. I'm assigning the issue to Ops to figure out why it's failing so regularly and hopefully implement a fix.

**Comment by chcosta** [comment] 2024-02-16 20:43
Filed - https://github.com/dotnet/dnceng/issues/2034

The issue was kind of silly.  The web page was offline because something added the app_offline.htm page to the root of the website -
[App Offline file (app_offline.htm) | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/app-offline?view=aspnetcore-8.0)

I was able to get the website running by going in the Azure portal to dotneteng-status-staging (Web App) -> Advanced Tools (under the Development Tools section) -> Go ->  Debug console (top of the page) -> CMD -> navigate to
`site\wwwroot`, and running `del app_offline.htm` (which I felt safe doing based on the documentation).

it's not clear to me what added the file.  From what I can tell, the file is generally explicitly added, or explicitly added to a deployment process and not some magic thing that aspnet is doing.

**Comment by chcosta** [comment] 2024-02-20 17:20
Closing this issue as the problem is resolved.  If the file re-surfaces, we'll have to track down what is adding it.

**Closed by chcosta** 2024-02-20 17:20 UTC
Labels: Ops - Service Maintenance
