### ISSUE TITLE
windows.11.arm64.open has missing heartbeats

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1154] opened 2023-10-24 15:01 UTC
the windows.11.arm64.open queue has currently 200 machines in the scale set, but only 4 of them are heartbeating. This is using our core quota for no good reason. Investigate.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment] 2023-10-24 19:58
There's something going on with this scale set.

After some time, the machines will change their Status in Azure from running to "succeeded" and when that happens, they stop heartbeating. Cleaned up more failed machines, and still investigating. Will see if I can get a repro somewhere where I can connect to an affected machine.

**Comment by riarenas** [comment] 2023-10-27 15:04
The vm cleaner fixups have helped with the slow growth of non-heartbeating VMs, but we are still losing heartbeats.

**Comment by riarenas** [comment] 2023-10-30 17:18
Ah, there's mention of offline conversations. I guess that's where that was discussed.

**Comment by AlitzelMendez** [comment] 2023-10-30 20:34
update:

for the machines in "Succeeded" status:
These machines don't appear in our tables at all, looks like they never did heartbeat, and when trying to remote into them they return a "deallocated status", although this allocated status is not visible when just looking at the instances, which is not the expected. 

In the good news looking at our cost in the last months it doesn't seem to be a problem, so my guess is the machines are actually deallocated and we are not getting billed from them, but of course there are a couple of problems:
- why so many machines are failing to be created on this queue? (we can't have any logs which makes this super hard to investigate)
-  why is reporting succeeded instead of deallocated? is that particular thing only happening on this queue? I need to verify to see if we need an IcM

for this issue I will check also if we really on the instance to say deallocated to calculate things, and if the fact that is not returning deallocated is causing any trouble.

for the machines that are "Offline" in our side: some machines are staying in this status for hours, verifying this :)

**Comment by AlitzelMendez** [comment] 2023-11-01 23:34
Update:

I create a scale set: [almend-othertest - Microsoft Azure](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/HelixImages/providers/Microsoft.Compute/virtualMachineScaleSets/almend-othertest/instances) and 9 machines, as this issue is happening quite often I expected to find something in the machines:
![image](https://github.com/dotnet/dnceng/assets/6895254/24a5ee9a-2c44-4520-9cf9-8a3ee87cf841)


I was able to initialize 6 machines and make them heartbeat  
![image](https://github.com/dotnet/dnceng/assets/6895254/90a71515-664b-456c-aa03-1a477c980ccc)

but I had 3 problematic machines and the problem is that I was unable to connect to those machines, my user and pwd wasn't working, I need to mention that as they were part of an scale set they had the same user a pwd for all the machines... but in some it was not working

so far my guess is that something like that is happening, that there are machines that are failing to even create the user and at the end they don't heartbeat and is the reason that we don't have logs or anything 

I will keep looking but giving the amount of machines I tried to run this and that the rest of them worked I will focus on the 3 that didn't work , well I will keep 1 machines that didn't work and delete the rest of the machines :)

**Comment by AlitzelMendez** [comment] 2023-11-02 19:15
I just found out or at least notice that we could activate the boot diagnostics on this scale set to see how things were progressing on the machines until the time it was just broken :)

I activated this (temp) in HelixStaging and scale out the scale set to maybe 4 machines and followed the screen shots of the machines 😄  only 1 of the machines did heartbeat at the end... the rest were stuck

the machines that didn't had a heartbeat ended up with this last screenshot: 
![image](https://github.com/dotnet/dnceng/assets/6895254/9f6fa6b1-709d-4614-943c-7166487e02dd)

so it looks like the machines are getting stuck in there, I know that doesn't provide much info, why some machines are showing this and other no? why only on this queue? I will look how we get rid of this usually but tbh looks like an IcM 😢 

the machine that had a heartbeat went to an entire different process, I saw everything even the logs when helix was running.... so yes this is makis the machines not run helix because they are just stuck in there

**Comment by riarenas** [comment] 2023-11-02 19:40
Ooh that's a good find on the machines getting stuck in what looks like OOBE? 

Some next steps that occur to me:
* Is dhandler running in the machines that get stuck in this prompt? In theory the custom script extension is running even in the broken machines, and the first-run should start dhandler, maybe we need to start it earlier? 
* If you click through all the dialogs, do we eventually get a heartbeat?
* Do we have a new image version for this? Does it repro in that new image?
* If we don't have a new image ready, how about using an old one? does it repro there?

At that point it looks like maybe a windows bug, and then we'd have to track down how to think about this.

**Comment by AlitzelMendez** [comment] 2023-11-02 21:19
- I will reach you our for the dhandler 
-  There are a bunch a limitation because I can't interact with the machine, I am able to see it like an omnipresent narrator, but I can't intervene, which means I can't click through the dialogs :/ and I can't RDP to any machine on this state because the RDP Settings broken, I already tried using bastion, resetting passwords
- For the versions, on my staging test I tested 2023.1026.033040 that is the latest, in prod we have an older one 2023.1023.033535
I will try with an older version as looks like this got worst after the 26, please consider that the vm cleaner was fixed on the 18 so this is real data: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/34467

![image](https://github.com/dotnet/dnceng/assets/6895254/f912c5e8-34af-430b-ac76-8ff204f5a180)

those are all the arm machines that were not hearth beating!

Also looking into all the queues looks like are more machines kind of impacted if we see all the queues: [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2OOw7CMBAFe07xlMqRokg5AB0Np0Abe4mt4DV41%252BIjDk%252BKiH5mNFbJsx6%252BeEaujMyqtDB8EaMkii6S4kZ%252B5QBCZKo2MxmupWKCj%252BxXHbvN55exBDwaNz6HC46wolaTLM43tZJPKbNoKqLjDvWbpi1nqunDCL40Mbcf9Jjf%252F9iAOYmzLaBG%252BT5gCv0PziZnJLkAAAA%253D/timespan/2023-10-18T20%3A46%3A50.000Z%2F2023-11-02T20%3A46%3A50.733Z) and one that looks pretty unhappy is ubuntu.1804.armarch.open

**Comment by AlitzelMendez** [comment] 2023-11-02 21:46
I tested with older version `2023.1004.172651` and same problem 😞

**Comment by AlitzelMendez** [comment] 2023-11-06 18:09
I did a more complete test of a previous version as I noticed that this started happening more heavily after the rollout, which makes me thing that it was related to this [Pull request 34761: [Rollout] Production rollout, 2023-10-25 - Repos (azure.com)](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34761), so I reverted the version changed on this DNM PR: [Pull request 35052: [DNM] Draft to test if a image 11 arm version introduced an error that we see in prod - Repos (azure.com)](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35052)


My findings were that even before this version machines were failing to heratbeat but with a completely different error, so this error of not being able to log in into the machine and that is stuck of selecting the region looks like is completely related to the version 22621.2428.231001

This is a market place image: ```Get-AzVMImage -Location westus -PublisherName microsoftwindowsdesktop -Offer windows11preview-arm64 -Skus  win11-22h2-ent ``` and as you can see the problem is with the latest version, so I think we could revert this version (although looks like previous version also had other problem so we will need to also correct that) and open an IcM to report the problem with this version of the image, I talked with Ilya and he suggested opening the issue with: https://1esbot-prod.azurewebsites.net/?Service=AzureDevOps

**Comment by riarenas** [comment] 2023-11-06 18:13
It's not clear to me where Azure Devops enters the picture here. Can you clarify?

**Comment by AlitzelMendez** [comment] 2023-11-06 18:21
pretty sure wasn't the service, I just copy pasted the link with info that was not needed, and the only suggestion for @ilyas1974 
 was opening this using 1ES bot :)

**Comment by epananth** [comment] 2023-11-06 22:12
Created an ICM for this https://portal.microsofticm.com/imp/v3/incidents/details/439194915

**Comment by ilyas1974** [comment] 2023-11-10 15:46
Currently have a mail thread with the support team to work on getting this resolved.

**Comment by ilyas1974** [comment] 2023-11-29 19:14
Change from 1ES team is currently being deployed to our environment and should be completed by 12/1.

**Comment by ilyas1974** [comment] 2023-12-04 16:26
ICM related to this issue - https://portal.microsofticm.com/imp/v3/incidents/incident/438329774/summary has been resolved. Closing this issue.

**Closed by ilyas1974** 2023-12-04 16:26 UTC
Labels: Ops - First Responder
