### ISSUE TITLE
Add nuget authentication to source index template

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#923] opened 2023-09-29 18:56 UTC
The template https://github.com/dotnet/arcade/blob/main/eng/common/templates/job/source-index-stage1.yml is currently not supporting authentication, which now is needed because astra is still private.

This is causing the following error: 

```
System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-libraries-internal/nuget/v3/index.json.)
D:\a\_work\1\s\artifacts\toolset\restore.proj : error :  ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-libraries-internal/nuget/v3/index.json.
D:\a\_work\1\s\artifacts\toolset\restore.proj : error :  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
 
```

this was reported in teams: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1696011282938?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1696011282938&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1696011282938

In order to fix this we need to add nugget authentication: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines&viewFallbackFrom=azure-devops to the template  https://github.com/dotnet/arcade/blob/main/eng/common/templates/job/source-index-stage1.yml

as this is a private repo we need to add source indexing 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by joperezr** [comment] 2023-10-05 22:34
We are still hitting this. Have we made any progress on figuring out what might be causing this?

**Comment by riarenas** [comment] 2023-10-05 22:45
The root cause is understood. The repo has a feed that requires authentication in their Nuget.config. This is not expected for public .NET repos, so we never hit this when source indexing the other repos.

Thinking about this scenario, do we want to enable it in the first place? I don't think we ever want to source-index private repos, or repositories that are not buildable due to requiring authentication in the nuget.config.

**Comment by riarenas** [comment] 2023-10-10 15:26
I think we should close this for now. In this particular case it seems like it's a scenario we don't want to enable as it could cause mixed signals if a private repo or a repo that contributors would need to auth against shows up in the source indexer.

If we get another scenario where we need to consider authenticating against private feeds when indexing we could revisit.

**Closed by riarenas** 2023-10-10 15:26 UTC
Labels: Ops - First Responder
